version: "3.7"

services:

  bookstore:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookstore_server  
    ports:
      - "8082:8082"
    volumes:
       - ./source:/go/src/github.com/igorlev91/GlobantBookStore/source
    env_file: 
      - ./setting.env  
    depends_on: 
      - db
    
    networks: 
      - inner_host  

  db:
    image: mysql:latest
    volumes:  
        - "./source/database/migrations/bookstore_db.sql:/docker-entrypoint-initdb.d/bookstore_db.sql"
      
    container_name: bookstore_database
    ports:
     - "6033:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "pseudo_pass"
      MYSQL_DATABASE: "bookstore"
      MYSQL_USER: "book_manager"
      MYSQL_PASSWORD: "pseudo_pass"
      MYSQL_HOST: "bookstore_database"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"    
    env_file: 
       - ./setting.env  
    networks: 
       - inner_host
    restart: on-failure      
networks:
    inner_host:
        driver: "bridge"
          
#volumes:
#    dbdata:
