version: "3.7"

services:

  bookstore:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookstore_server  
    ports:
      - "8082:8082"
    volumes:
       - ./source:/go/src/github.com/igorlev91/GlobantBookStore/source
    env_file: 
      - ./setting.env  
    depends_on: 
      - db
    
    networks: 
      - inner_host  

  db:
    image: mysql:latest
    volumes:  
      - book_store_mysql_data:/var/lib/mysql
      
    container_name: bookstore_database
    ports:
      - '3406:3306'
    environment:
      
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    
    env_file: 
       - ./setting.env  
    networks: 
       - inner_host
    restart: on-failure      
networks:
    inner_host:
        driver: "bridge"
          
  
volumes:
    book_store_mysql_data:
