version: "3.7"

services:
  db:
    container_name: "test_db"
    build:
      context: .
      dockerfile: db.Dockerfile
    networks:
      - default
    restart: always
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    # setting some env vars to create the DB
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "test"
      MYSQL_DATABASE: "book_store"
      MYSQL_USER: "test_user"
      MYSQL_PASSWORD: "test"

    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  api:
    container_name:  "test_api"

    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"

    depends_on:
      - db

    volumes:
      - .:/source/
