version: "3.7"

services:

  bookstore:
    build:
      dockerfile: Dockerfile
    container_name: bookstore_server  
    ports:
      - 3000:3000
    volumes: 
      - ./source:/go/src/source
    env_file: 
      - ./setting.env  
    depends_on: 
      - db
    networks: 
      - inner_host  

  db:
    image: mysql:latest
    volumes:
      - bookstore_data:/var/lib/mysql
    container_name: bookstore
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    
    env_file: 
       - ./setting.env  
    networks: 
            - inner_host
networks:
    inner_host:
        driver: "bridge"  
  
volumes:
    bookstore_data:
