version: "3.7"

services:

  bookstore:
    build:
      dockerfile: Dockerfile

    ports:
      - "8080:8080"
    volumes: 
      - ./source:/go/src/source
    env_file: 
      - ./setting.env  
    depends_on: 
      - db
         

  db:
    image: mysql:latest
    volumes:
      - bookstore_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: bookstore
    env_file: 
       - ./setting.env  

    ports:
      - "3306:3306"
  
volumes:
    bookstore_data:
