version: "3.7"

services:

  bookstore:
    build:
      dockerfile: Dockerfile
    environment:
      BOOKSTORE_DBDRIVER: mysql
      BOOKSTORE_DATABASE: root:@tcp(db:3306)/bookstore
    ports:
      - "8080:8080"

  db:
    image: mysql:latest
    container_name: mysql_docker
    volumes:
      - bookstore_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: bookstore
    ports:
      - "3306:3306"

volumes:
    bookstore_data:
